#!/bin/sh

#### NOTE: THIS SCRIPT MUST BE EXCUTED WITH SUDO #####
if [[ $EUID -ne 0 ]]; then
echo "This script must be executed as root user."
exit 1
fi

# Source this file in your shell config file if you want 
cd $(realpath $0 | sed -e 's/add-extra-paths//g')
dirArray=$(realpath ./ ./*/ ./*/*/)
# use file globbing to put subdirectorites of ./scripts into an array

echo ${dirArray[@]} | tr " " "\n" > /etc/paths.d/my-scripts
