#!/bin/zsh

scriptDirectoriesArr=( $( realpath ./*/*/ ) )
scriptCategoriesArr=( $( echo ${scriptDirectoriesArr[@]} | tr " " "\n" | awk -F/ '{print $NF}' ) )
category=$( echo ${scriptCategoriesArr[@]} | tr " " "\n" | choose )

for dir in $scriptDirectoriesArr
do 
  var=$(echo $dir | awk -F/ '{print $NF}')
  if [[ "$var" == "$category" ]]
  then 
    script=$dir/$(ls $dir | choose)
    $script
  fi
done
