#!/bin/zsh

projects=(aarch64 bparser cops onebook raylib)
declare -A dirs
dirs[aarch64]="$HOME/git-dir/Personal Projects/learning/arm64"
dirs[bparser]="$HOME/git-dir/Public Projects/Bookmark Management/BookmarkParser/"
dirs[cops]="$HOME/git-dir/Public Projects/C Libraries/cops/"
dirs[onebook]="$HOME/git-dir/Public Projects/Bookmark Management/onebook/"
dirs[raylib]="$HOME/git-dir/Personal Projects/learning/c/raylib/"

for proj in $projects; do
	tmux new-session -s $proj -d -x- -y-
	tmux rename-window -t $proj:0 'Main'
	tmux split-window -t $proj:0 -l 12
	sleep 0.3
	tmux send-keys -t $proj:0.0 "cd \"$dirs[$proj]\"" Enter
	tmux send-keys -t $proj:0.1 "cd \"$dirs[$proj]\"" Enter
	tmux send-keys -t $proj:0.0 "clear" Enter
	tmux send-keys -t $proj:0.1 "clear" Enter
	tmux send-keys -t $proj:0.0 "nvim" Enter
	git -C "$dirs[$proj]" rev-parse 2>/dev/null && tmux send-keys -t $proj:0.1 "onefetch" Enter
done
