#!/bin/zsh

### define variables
plist=$HOME/.pass-list.txt
pacclist=$HOME/.pass-acc-list.txt

#### Choose pass item with choose-gui ####
PWORD=$(cat $pacclist | choose)

### retrieve password
# grep the full item name
ACCNAME=$(cat $plist | rg $PWORD)

if [[ $PWORD != "" ]]; then
# retrieve the password
pass -c $ACCNAME
# display that password was chosen successfully
echo Password Copied to Clipboard | choose -n 1
exit 0
else
exit 1
fi
